services:
  web:
    build:
      context: .
    ports:
      - 3000:5173 
    volumes:
      - .:/app # Mount the current directory to /app in the container
      - /app/node_modules # Protect the node_modules directory from being overwritten
